### PR TITLE
Present object destructuring in a cleaner way

### PR DESCRIPTION
**Pull request by feimosi**
Not to confuse the readers

### CODE REVIEW

**Comment by metagrover** [comment]
Hi @feimosi! Wouldn't this be more clear:

`let {a: x, b: y, c: z} = bar();`

**Comment by feimosi** [comment]
Yeah, that's also an option. I just wanted to avoid anything that could be written in a shorthand notation :)

**Comment by GoToLoop** [comment]
Should also mention that if property renaming is desirable, we need to specify them after a colon, like @metagrover's  example. Otherwise, use shorthand trick in order to create a variable w/ the same name as destructed property.

**Comment by feimosi** [comment]
Yeah, that could also be added.

**Pull request merged**
